spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    username: ${RABBIT_USERNAME:ddynamo}
    password: ${RABBIT_PASSWORD:ddynamo}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 4040